### ISSUE TITLE
如何看待这篇文章？

### ISSUE THREAD

**Issue by theharveyz** [xiaolai/INB-Principles#4]
[外围女，个体户，骗子，传销，韭菜，这是你不知道的比特币江湖](http://mp.weixin.qq.com/s/APbIrY8_5AMfbVl5Oc5uRw)

**Comment by ghost** [comment]
👎🏿👎👎👎👎👎👎👎

**Comment by ghost** [comment]
这傻x，广告做到这来了。

**Comment by theharveyz** [comment]
@VeniVediVeci  这只是看到一篇文章，什么广告？
